export const START_ASYNC_OP_WATCHLIST = "START_ASYNC_OP_WATCHLIST";
export const END_ASYNC_OP_WATCHLIST = "END_ASYNC_OP_WATCHLIST";
export const RESET_WATCHLIST_OP_STATUS = "RESET_WATCHLIST_OP_STATUS";

export const START_ASYNC_OP_STOCK = "START_ASYNC_OP_STOCK";
export const END_ASYNC_OP_STOCK = "END_ASYNC_OP_STOCK";
export const REMOVE_STOCK_OP_STATUS = "REMOVE_STOCK_OP_STATUS";

export const LOAD_WATCHLISTS = "LOAD_WATCHLISTS";
export const LOAD_WATCHLISTS_SUCCESS = "LOAD_WATCHLISTS_SUCCESS";
export const LOAD_WATCHLISTS_ERROR = "LOAD_WATCHLISTS_ERROR";

export const FETCH_QUOTES = "FETCH_QUOTES";
export const FETCH_QUOTES_SUCCESS = "FETCH_QUOTES_SUCCESS";
export const FETCH_QUOTES_ERROR = "FETCH_QUOTES_ERROR";

export const CREATE_WATCHLIST = "CREATE_WATCHLIST";
export const EDIT_WATCHLIST = "EDIT_WATCHLIST";
export const SAVE_WATCHLIST_SUCCESS = "EDIT_WATCHLIST_SUCCESS";

export const DELETE_WATCHLIST = "DELETE_WATCHLIST";
export const DELETE_WATCHLIST_SUCCESS = "DELETE_WATCHLIST_SUCCESS";

export const ADD_STOCK = "ADD_STOCK";
export const EDIT_STOCK = "EDIT_STOCK";
export const SAVE_STOCK_SUCCESS = "SAVE_STOCK_SUCCESS";

export const DELETE_STOCK = "DELETE_STOCK";
export const DELETE_STOCK_SUCCESS = "DELETE_STOCK_SUCCESS";
