// Toasts Actions
export const ADD_TOAST = 'ADD_TOAST';
export const REMOVE_TOAST = 'REMOVE_TOAST';

// Quote Actions
export const FETCH_QUOTES = 'FETCH_QUOTES';
export const FETCH_QUOTES_SUCCESS = 'FETCH_QUOTES_SUCCESS';
export const FETCH_QUOTES_ERROR = 'FETCH_QUOTES_ERROR';
export const SET_QUOTES_INTERVAL = 'SET_QUOTES_INTERVAL';

// Watchlists Actions
export const LOAD_WATCHLISTS = 'LOAD_WATCHLISTS';
export const LOAD_WATCHLISTS_SUCCESS = 'LOAD_WATCHLISTS_SUCCESS';
export const LOAD_WATCHLISTS_ERROR = 'LOAD_WATCHLISTS_ERROR';

export const SELECT_WATCHLIST = 'SELECT_WATCHLIST';
export const CREATE_WATCHLIST = 'CREATE_WATCHLIST';
export const EDIT_WATCHLIST = 'EDIT_WATCHLIST';
export const SAVE_WATCHLIST_SUCCESS = 'EDIT_WATCHLIST_SUCCESS';

export const DELETE_WATCHLIST = 'DELETE_WATCHLIST';
export const DELETE_WATCHLIST_SUCCESS = 'DELETE_WATCHLIST_SUCCESS';

// Stock Actions
export const ADD_STOCK = 'ADD_STOCK';
export const EDIT_STOCK = 'EDIT_STOCK';
export const SAVE_STOCK_SUCCESS = 'SAVE_STOCK_SUCCESS';

export const DELETE_STOCK = 'DELETE_STOCK';
export const DELETE_STOCK_SUCCESS = 'DELETE_STOCK_SUCCESS';

// Operations
export const INIT_OP = 'INIT_OP';
export const START_OP = 'START_OP';
export const UPDATE_OP = 'UPDATE_OP';
export const END_OP_SUCCESS = 'END_OP_SUCCESS';
export const END_OP_ERROR = 'END_OP_ERROR';
export const REMOVE_OP = 'REMOVE_OP';
