export const LOAD_WATCHLISTS = "LOAD_WATCHLISTS";
export const CREATE_WATCHLIST = "CREATE_WATCHLIST";
export const EDIT_WATCHLIST = "EDIT_WATCHLIST";
export const DELETE_WATCHLIST = "DELETE_WATCHLIST";